version: '2'

services:
  faceapi:
    image: node:9.8.0
    environment:     
    - VIRTUAL_HOST=faceapi.boldware.cl
    - VIRTUAL_PORT=80 
    expose:
      - "80"
    volumes:
      - ShareImages:/data/
  recognition:
    image: pythonenv:latest
    restart: always
    working_dir: ShareImages:/data/
    command: sh -c 'sh -c 'pip install -r requirements.txt; python server.py -h 0.0.0.0 -p 8000 -d ../examples/images'
    volumes:
      - ShareImages:/data/
    expose:
      - "8000"
    links:
      - faceapi

networks:
   default:
      external:
         name: nginxproxy_nginx-network

volumes:
   ShareImages: