version: '2'

services:
  recognition:
    image: pythonenv
    restart: always
    environment:     
    - VIRTUAL_HOST=recognition.boldware.cl
    - VIRTUAL_PORT=80    
    command: sh -c 'ls;mkdir examples;cd examples; mkdir images; mkdir downloads; cd .. ; pip install --upgrade pip; pip install -r requirement.txt; python server.py -h 0.0.0.0 -p 80 -d ./examples/images'
    volumes:
      - ./:/usr/src/app  
    working_dir: /usr/src/app
    expose:
      - "80"
  faceapi:
    image: node:9.8.0
    restart: always
    environment:     
    - VIRTUAL_HOST=faceapi.boldware.cl
    - VIRTUAL_PORT=80
    command: sh -c 'npm install; npm run start' 
    expose:
      - "80"
    volumes:
      - ./:/usr/src/app  
    working_dir: /usr/src/app
    links:
      - recognition

networks:
   default:
      external:
         name: nginxproxy_nginx-network

volumes:
   ShareImages: