version: '2'

services:

  recognition:
    image: pythonenv
    restart: always
    expose:
      - "8000"
    volumes:
      - .:/ShareImages
    working_dir: /ShareImages
    command: 'sh -c 'pip install -r requirements.txt; python server.py -h 0.0.0.0 -p 8000 -d ../examples/images'
  faceapi:
    image: node:9.8.0
    restart: always
    environment:     
    - VIRTUAL_HOST=faceapi.boldware.cl
    - VIRTUAL_PORT=80 
    volumes:
      - .:/ShareImages
    working_dir: /ShareImages
    command: sh -c 'npm install; npm run start'
    links:
      - recognition
    expose:
      - "80"
volume:
  ShareImages
networks:
   default:
      external:
         name: nginxproxy_nginx-network