version: '2'

services:
  faceapi:
    image: node:9.8.0
    restart: always
    environment:     
    - VIRTUAL_HOST=faceapi.boldware.cl
    - VIRTUAL_PORT=80 
    volumes:
      - .:/ShareImages
    working_dir: /ShareImages
    command: sh -c 'npm install; npm run start'
    ports:
      - "80:3500"
    expose:
      - "80"
      
networks:
   default:
      external:
         name: nginxproxy_nginx-network